replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: hyundooboo/rtm-eureka-service
  pullPolicy: IfNotPresent
  tag: "3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: eureka-service
  environment: production

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8761

ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: ""
  hosts:
    - host: rtm.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8761
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8761
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector:
  nodegroup: "spring"

tolerations: []

affinity: {}
