apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/Ready-to-Marry/RTM_infra # 여러분의 Git 저장소
    targetRevision: main
    path: elasticsearch
    helm:
      chart: elasticsearch
      repoURL: https://helm.elastic.co
      version: 8.5.1
      valueFiles:
        - "elasticsearch/values.yaml"   # Git에서 values.yaml을 참조
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
