apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-sync-two
  namespace: spring
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
        - name: wait
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for services to be ready..."
              for i in $(seq 1 30); do
                if kubectl get pods -l app=user-service -n spring | grep "1/1" | grep "Running" &&
                   kubectl get pods -l app=partner-service -n spring | grep "1/1" | grep "Running" &&
                   kubectl get pods -l app=admin-service -n spring | grep "1/1" | grep "Running"; then
                  echo "All services are ready!"
                  exit 0
                fi
                echo "Not all services are ready yet..."
                sleep 5
              done
              echo "Timed out waiting for services"
              exit 1
      restartPolicy: Never
  backoffLimit: 0