apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-sync-zero
  namespace: spring
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: wait
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Eureka to be ready..."
              for i in $(seq 1 30); do
                if kubectl get pods -l app=eureka-service -n spring | grep "1/1" | grep "Running"; then
                  echo "Eureka is ready!"
                  exit 0
                fi
                echo "Not ready yet..."
                sleep 5
              done
              echo "Timed out waiting for Eureka"
              exit 1
      restartPolicy: Never
  backoffLimit: 0