---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCnhzCIKX9zrfSIPjtpiknYQmIOFXxU19Q+Eh+8mK1Snf57MtwcZUJMkPXJuI9X0FeovASbMEUHoyT5M/RD8TbOQ2JKwg9+FiIKg8qDUxfZE9n+/996JYRjDdwrYviGIySU2Ft6mTLNPe8xXoWpeGI1mKFEGeTH8AQ7ujXgHYuFyIX0rr7LQXmLZgs/4ZpzRhDu/Bec4eioqgHy6XeXJHmi7EdIrWD3TViF8dgDO3sOxqko0WCedy4vNJhlW+aFmHxWM/jh3K/iB05moU3Uw643RUDOAE3VcdyJjEYA3OSq9f3CpFVpmCEglgBDik/3iMG5GThZID3L3d+T0rd+2iqYKX0Pz8NAir0L32rDjO+/3Rrn8PT4X38snbhPgtsdPhRPvzg2XYfkjn1W05r4DKVoY2dBSi8oDYI3Gr9lpuIqVWGIPdWzayExv7elfvjfplsAv9tsPfB96JHnv7G0gnR7mKof+hwiveg265gYCtAuvdL0aDYAPrBD8EV5F+S8xp2UcIlHspiEru0cHrdx6ur7+/lqpW7v6xrgHp0ZyX/AzJ6/+EvffqFMBgRUzrlFT/4Vh3Lm5YLMgUd5rPvT7mgGC51HGBqCZlvSb6xz/93h0Ln6AwYXo+3ruFSa5Ii2MF8cmcEOQvA6B/+hkabOnpsJt9D7HoLzlDwYhTyKS+gwS3beXQD666z0o3MOmmdXbZQsPccwXtqqLDs=
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth-secret
      namespace: redis
