---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgA39ZNFgFy+nqOH9HeT39BssefHuW0CiiqpSomT6t2J2+f8EtcSi9yIxBEnIZZMBtIdGdeGaUJZoFvUxPhn09estkXU0TSeZQ2oV4Xqhu37B6Q01Oc8kj012rwouZx/wzOLrY5TMiZoL3uyETX3bxWv4kz8+VrffPuRcV1n80jgTPcygVkHqtDPixKSSdr0QTEwkI7YnvdNAqRtDRkiQLYa7b0+Yf8DX5+xdOEbiHfENaTIeqQQJPDCXQvU4Ls1Jww8WOHHmiXl26pubjjQ6JpANV8p1976j7ItNEn7GpRGmT/q65ETqzigp9YsegjoX8ylUDKlwj4KOgcdzskTb6lH6mZJQzoTQdOS8EMCmiIdoW9Bz7qxEKpYvWB7ZlT31F1UUS3Ttuy6MvCyM6aiLavU7aYEN7w/LZ9cGWMdiUXYiM2LzIa5MGnm3smhCb/dO7Vh3YYdvO/nOeSZKUgma5djNPWGC/B5EJLMIQ0GuWBkRPkI/wOLcg2pVIWegfJMymAs/E/eNp8cdKQ+WQPR5MFp7yAI+h/1L9IzbQjOq/7VgFGl8xW49+KkVv3vIzS02NKoTmwR7pMj5IkrY3wr4SfE+SJ+V5S9eP35vYqmXvjXZ82HYYXGwbVnUCbl2JAVi09xl027gvev7rWFfsKsZm34ObFjALWIu+Ky02yGngMdgjVxhKwC+74xrtXdXMfPBUKtKJ5k0Cupkdw=
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth-secret
      namespace: redis
