apiVersion: batch/v1
kind: Job
metadata:
  name: wait-sync-three
  namespace: spring
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: wait
          image: bitnami/kubectl:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "Waiting for services to be ready..."
              for i in $(seq 1 30); do
                if kubectl get pods -l app=catalog-service -n spring | grep "1/1" | grep "Running" &&
                   kubectl get pods -l app=reservation-service -n spring | grep "1/1" | grep "Running"; then
                  echo "All services are ready!"
                  exit 0
                fi
                echo "Not all services are ready yet..."
                sleep 5
              done
              echo "Timed out waiting for services"
              exit 1
      restartPolicy: Never
