---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rtm-gateway-service-secret
  namespace: spring
spec:
  encryptedData:
    JWT_SECRET_KEY: AgADq5gPj61jxmDXjgat7B9zLLC8uYd/X40Sd16byliGzz4TfclPn8KTxSvOv2yr3ulpOZSH5F8Y1IAaFdrTxm6h+Pl1felE8uZ8/KeCvgadSfdNTVsm2QHc5qa18vL9wPGv+9Z9OtOztAWgq62ed2sePL2xHfVk8jlBCVSwcJ65vyLp37cC9F8nVN+9JdTnVBvFdxEbjC3TM8PL6kbxDjqVcrYWj4ETzrkOvJvModuaFEv77+D4HuRUl9zvdijCpmQySOw6K8MiVrTv5SXd6YhrSTL0e86GZGO2gTMR3m9aOvNl61g5D6KIcqfL1ZN79ZaBwRU1OMB+wLNAaOXBE3zYNUyu/9oDvjYD6MXzbAhm+mAyuHyN4AuM4dH1Kxu2WeHDb1zR+Bf+IwxjO4OuIS/kbF6SGuLlK7tNqNMFgWY1lieORJ6bwhrGlP2Hc9dFmC+yrUo9CBBj2n9TSpTALjtU6CgAh8VH5dO5i5QmZIPkmBDlM7EYkBFaDpMg2xXh9iXJ5lb2cu+LHOfvYeNOzbDDs2t2Nj/DyEaMj9uRu9ftye8qHS07dHs5sbp/ZirEH/P9yX8MihkK/U68fVIRXLPEapZAnzFq8VGPvzM3rV1Y+c/2HpHCpoIX64I6nq30lQ1h5FvoWpftN7UeQw22BOkwUUMGCEqvZhP2Oyss9u2grJhlbIWKB9SJxuCbIB0Odtqh3bj70HT87Q2IHP+iboD5oMkR0joexVJZxyaQ0LFk7aYS3aFDB35RLDlGXw==
  template:
    metadata:
      creationTimestamp: null
      name: rtm-gateway-service-secret
      namespace: spring
