---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rtm-gateway-service-secret
  namespace: spring
spec:
  encryptedData:
    JWT_SECRET_KEY: AgAUzZwAXN9rp/1Qc5Ems3AZIjOGfr52XQBih8/ONPDnY/G02kwlcwqJzT8QZsP/BNAj6nlQzBB+1x/7/y2ZmZ4PesRm+0P25IUb4NYIbYVxB+6Q3LZxWYf+RZx4FQAqdch0e3DrF3XXFuWemjJKZHNuN4pOBditB9qWlURK6V3rD5Df4A6VyB4r7uYgbqjd/8sQYPTc09bmqQeswaITdWUbuqnX1hUl1vxo1csBbYbsYmxBmOSoP1VWNk1xIxyeMFd+Dr3oWz60Efgy7HofFMkQI8ZoCD1+GM+zQbrmRO3+ThK5XrzF1lOAlZLWKcWLa4EDptTrA3c6Tje0+bOGxcgj2xPDXT5J5Kz1D6+HGJjdN0kF+VkrvBNbEW4kBIxXS+MBaufsMDxYUQQJ0uJUcuqegOj3PIkl0Twa3e3OB/AyY1n95k+p/ZXhG8ycTHkD7yNabK5XJv0YYZRN7qmqMKnsHyVjFr0oIPQAcB3HAJaqUSRDuIXRZR8XkCxp7h0777lrmQEWd3AKdhI4yqREdY9QSVz0tBs4G1QbnVlUUpi1eM21JczOpOf9AP2OEu1VxV/5yXnzZeCBqvPi+iPtS94PbQ5pz0dCcQC+j48eUh38+KOzTREuw1euROOC+jghIaVrVF1g3zC1nEuRtgvlDQurCGuGZDswq5rCPeJp+5dB7OEk7SJl43zMa6P3J9FKb5AR2yAGYi+60LE2CMQRBgVxUqNESPv+JdXhyAmJ++HY+auyjiLDmZMpw6yPNw==
  template:
    metadata:
      creationTimestamp: null
      name: rtm-gateway-service-secret
      namespace: spring
