apiVersion: batch/v1
kind: Job
metadata:
  name: wait-sync-zero
  namespace: spring
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: wait
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "🔎 Waiting for Eureka..."
              for i in $(seq 1 30); do
                if kubectl get pods -l app=eureka-service -n spring | grep "1/1" | grep "Running"; then
                  echo "✅ Eureka is ready!"
                  exit 0
                fi
                echo "⏳ Not ready yet... ($i/30)"
                sleep 5
              done
              echo "❌ Timed out waiting for Eureka"
              exit 1
      restartPolicy: Never
