apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Ready-to-Marry/RTM_infra
    targetRevision: onprem
    path: admin-service
  destination:
    server: https://kubernetes.default.svc
    namespace: spring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
