replicaCount: 2
revisionHistoryLimit: 2

image:
  repository: hyundooboo/rtm-gateway-service
  pullPolicy: IfNotPresent
  tag: "5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: gateway-service
  environment: production

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8089

ingress:
  enabled: true
  # ALB Ingress Controller가 인식하는 ingress class 이름 (보통 'alb' 또는 'aws-alb' 등)
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    # 인터넷용 ALB, 내부용은 internal
    alb.ingress.kubernetes.io/scheme: internet-facing
    # 'ip' 또는 'instance' (보통 ip 권장)
    alb.ingress.kubernetes.io/target-type: ip
    # HTTP 80포트 리스닝
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-port: "8089"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8089
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8089
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector:
  nodegroup: "spring"

tolerations: []

affinity: {}

env:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

secrets:
  db:
    secretRef: rtm-gateway-service-secret